### ISSUE TITLE
Use of guids in db structure

### ISSUE THREAD

**Issue by degree451** [ayende/rhino-security#1]
Is there any way you could convert this code base to utilize integers rather than guids for the primary keys? Guids have the worst performance out of all of the database types and take the most space to store. The use of guids in this project also dictates that users of this framework must also utilize guid types whenever they have a table that needs a foreign key to the user's id column. Perhaps there is a compromise where the data type can be controlled via a setting?

**Comment by ayende** [comment]
Degree,
No, it is not going to be possible.
The reason that we use guids internally in RS is that we need to be unique without hitting the DB.
Note that RS is using always incrementing guids, so you don't have indexing problems.

Note that you don't have to have guid FK in your system, RS allows you to use integers for your entities, it will just use guids internally.

**Comment by degree451** [comment]
Ah, I see how it works now. Thanks!
