### ISSUE TITLE
'Rhino.Security\Properties\AssemblyInfo.cs' could not be opened 	Rhino.Security-vs2008

### ISSUE THREAD

**Issue by ToJans** [ayende/rhino-security#3]
Apparently Rhino.Security/Properties/assemblyinfo.cs is missing in the latest version. I do not know whether it is required or not, but building this in vs2008 fails.

**Comment by ToJans** [comment]
If you remove the file from the solution, you can build the DLL, but there is no assembly-info included.

**Comment by dschilling** [comment]
I haven't tried building this specific project, but AssemblyInfo.cs files are often generated by the build script.  Follow the instructions in http://github.com/ayende/rhino-security/blob/master/How%20to%20build.txt .  I bet that after you do that, the AssemblyInfo files will exist and Visual Studio will be happy.

**Comment by ayende** [comment]
As dschilling said :-)

**Comment by ToJans** [comment]
Ahum... my apologies for another case of RTFM... ;-)

**Comment by cpistiner** [comment]
Hi all! 

I've the same problem. I followed the steps in Howtobuild.txt but AssemblyInfo.cs don't exist. When i run the command: psake.ps1 default.ps1 don't have errors messages (but not sucessful).
